[2023-03-16 16:15:55,987] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: our_first_dag_v3.third_task manual__2023-03-16T07:15:51.145784+00:00 [queued]>
[2023-03-16 16:15:55,990] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: our_first_dag_v3.third_task manual__2023-03-16T07:15:51.145784+00:00 [queued]>
[2023-03-16 16:15:55,990] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-16 16:15:55,990] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2023-03-16 16:15:55,990] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-16 16:15:55,992] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): third_task> on 2023-03-16 07:15:51.145784+00:00
[2023-03-16 16:15:55,994] {standard_task_runner.py:52} INFO - Started process 99368 to run task
[2023-03-16 16:15:55,996] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v3', 'third_task', 'manual__2023-03-16T07:15:51.145784+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/var/folders/x1/7qlvjnbj06q1nkyhy70vbb2c0000gn/T/tmpktjwythp', '--error-file', '/var/folders/x1/7qlvjnbj06q1nkyhy70vbb2c0000gn/T/tmpkv3nv182']
[2023-03-16 16:15:55,996] {standard_task_runner.py:77} INFO - Job 10: Subtask third_task
[2023-03-16 16:15:56,009] {logging_mixin.py:109} INFO - Running <TaskInstance: our_first_dag_v3.third_task manual__2023-03-16T07:15:51.145784+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2023-03-16 16:15:56,021] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=byeonghwa
AIRFLOW_CTX_DAG_ID=our_first_dag_v3
AIRFLOW_CTX_TASK_ID=third_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-16T07:15:51.145784+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-16T07:15:51.145784+00:00
[2023-03-16 16:15:56,021] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/x1/7qlvjnbj06q1nkyhy70vbb2c0000gn/T
[2023-03-16 16:15:56,022] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, i am task3 and will be running after task1 at the same time as the task2 ']
[2023-03-16 16:15:56,024] {subprocess.py:85} INFO - Output:
[2023-03-16 16:15:56,026] {subprocess.py:89} INFO - hey, i am task3 and will be running after task1 at the same time as the task2
[2023-03-16 16:15:56,026] {subprocess.py:93} INFO - Command exited with return code 0
[2023-03-16 16:15:56,032] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=third_task, execution_date=20230316T071551, start_date=20230316T071555, end_date=20230316T071556
[2023-03-16 16:15:56,056] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-16 16:15:56,063] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
